version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10-stretch-browsers
      - image: mongo:latest
    steps:
       - checkout
       - run:
            name: install-npm-wee
            command: npm install
       - run: mkdir test-reports
       - run:
            name: install protractor for testing
            command: npm install -g protractor
       - run:    
            name: update webdriver-manager
            command: webdriver-manager update
       - save_cache:
            key: dependency-cache-{{ checksum "package.json" }}
            paths:
              - ./node_modules
       - run:    
            name: start webdriver-manager
            command: webdriver-manager start
       - run:    
            name: start testing
            command: protractor conf.js
      - run:
           name: code-coverage
           command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
           path: test-results.xml
           prefix: tests
      - store_artifacts:
           path: coverage
           prefix: coverage
      - store_test_results:
           path: test-results.xml
